### ISSUE TITLE
unable to run input array size of 1000 and order 3

### ISSUE THREAD

**Issue by AmareshPKandagal** [lakehanne/Savitzky-Golay#4]
Dear Lekan,

I was trying to smooth a signal of size 1000 samples with order 3. 
But when I execute I get output array size as polynomial order size.But output array should be the same size as the input array.
Could you help on same?

Thanks,
Amaresh P Kandagal

**Comment by robotsorcerer** [comment]
Please read the instructions here:

              https://github.com/lakehanne/Savitzky-Golay/blob/master/README.md

**Comment by AmareshPKandagal** [comment]
x: a vector of length 1000
I mean x is a vector of [x_1, x_2, ...., x_1000] 

 VectorXf X = VectorXf::Zero(990);

  FILE *fp_y;
  fp_y=fopen("niosy_data.txt","r");
  std::vector<float> x_v(1000);
  if (fp_y == NULL)
    cout<<"\n\nSpecified file is not found\n\n"<<endl;
    int i = 0; float Y_data = 0;

    while ((fscanf(fp_y, "%f", &Y_data)) != EOF)
    {
        x_v.push_back (Y_data);
       i++;
    }

Eigen::Map<Eigen::VectorXf> x(x_v.data(), 1000);
auto result = savgolfilt(x,3, 11);

--------------------
result ::    0    0    0    0    0 -nan    0    0    0    0    0

Could you help on same
