### ISSUE TITLE
./savgol do not work properly, please see comment

### ISSUE THREAD

**Issue by nichtgedacht** [lakehanne/Savitzky-Golay#6]
db@zweistein:/array_data01> git clone https://github.com/lakehanne/Savitzky-Golay.git
Klone nach 'Savitzky-Golay' ...
remote: Enumerating objects: 220, done.
remote: Total 220 (delta 0), reused 0 (delta 0), pack-reused 220
Empfange Objekte: 100% (220/220), 329.79 KiB | 0 bytes/s, Fertig.
Löse Unterschiede auf: 100% (123/123), Fertig.

db@zweistein:/array_data01> cd Savitzky-Golay
db@zweistein:/array_data01/Savitzky-Golay> mkdir build
db@zweistein:/array_data01/Savitzky-Golay> cd build/
db@zweistein:/array_data01/Savitzky-Golay/build> cmake ../
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28")
-- Checking for module 'eigen3'
--   Found eigen3, version 3.2.9
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
--         savgol include path:

-- /array_data01/Savitzky-Golay/include
--
eigen3 include path: /usr/include/eigen3

-- Configuring done
-- Generating done
-- Build files have been written to: /array_data01/Savitzky-Golay/build
db@zweistein:/array_data01/Savitzky-Golay/build> make
Scanning dependencies of target savgol
[ 33%] Building CXX object CMakeFiles/savgol.dir/savgol.cpp.o
[ 66%] Building CXX object CMakeFiles/savgol.dir/example.cpp.o
[100%] Linking CXX executable savgol
[100%] Built target savgol

db@zweistein:/array_data01/Savitzky-Golay/build> ./savgol
Frame size: 5;  Polynomial order: 3

 Vandermonde Matrix:
 1 -2  4 -8 16
 1 -1  1 -1  1
 1  0  0  0  0
 1  1  1  1  1
 1  2  4  8 16

Filtered values in the range
900 920 940 960 980
 are:
960 980 940 900 920

db@zweistein:/array_data01/Savitzky-Golay/build> ./savgol --help
==================================================
USAGE:

./savgol [<frame_size> [<polynomial_order> [<x_low> <x_high>] ] ]

       <frame_size>: odd int and ideally greater than
       <polynomial_order>:  an integer

       <x_low>, <x_high>: min and max limits of
       linspaced vector to be filtered.
===================================================
       Example: ./savgol 9 5

db@zweistein:/array_data01/Savitzky-Golay/build> ./savgol 9 5
==================================================
USAGE:

./savgol [<frame_size> [<polynomial_order> [<x_low> <x_high>] ] ]

       <frame_size>: odd int and ideally greater than
       <polynomial_order>:  an integer

       <x_low>, <x_high>: min and max limits of
       linspaced vector to be filtered.
===================================================
       Example: ./savgol 9 5

**Comment by robotsorcerer** [comment]
What’s the problem again?

**Comment by nichtgedacht** [comment]
Hi,

the problem is, that cmd: "./savgol 9 5" (example) is answered by showing the 
usage. Expected is a set of coefficients.

Regards
Dieter

Am Dienstag, 18. Dezember 2018, 12:03:09 schrieb Lekan:

**Comment by robotsorcerer** [comment]
You need to provide the data you are filtering too. Xmin & Xmax.

**Comment by nichtgedacht** [comment]
Hi

1.
even providing this it does not work:

db@zweistein:/array_data01/Savitzky-Golay/build> ./savgol 9 5 -100 200 

2.
according to usage  [<x_low> <x_high>] is optional

3.
 Example: ./savgol 9 5

Regards
Dieter

Am Dienstag, 18. Dezember 2018, 12:29:14 schrieb Lekan:
> You need to provide the data you are filtering too. Xmin & Xmax.
